### ISSUE TITLE
1.8.x RSA Fix

### ISSUE THREAD

**Issue by AndrewBabbitt97** [mesosphere/konvoy-image-builder#293]
#271 was added in 1.9.0 rather than 1.8.1, meaning we currently have to cherry pick and build this ourselves in order for AMIs to be built.

Kommander is not yet compatible with k8s 1.22.x, particularly due to removed APIs: https://docs.d2iq.com/dkp/konvoy/2.1/image-builder/create-ami/

Proposing a 1.8.1 release with changes from #271 added.

**Comment by jkoelker** [comment]
You can always specify a different k8s version: https://github.com/mesosphere/konvoy-image-builder/blob/main/docs/cli/konvoy-image_build_aws.md?plain=1#L26, is just the default. It can be specified in an `override.yaml` as well if that's more convenient (for source control and reproducibility of builds).

The documentation about this should be more clear about this.
