### ISSUE TITLE
Documentation Revisions For 1.9.0+

### ISSUE THREAD

**Issue by AndrewBabbitt97** [mesosphere/konvoy-image-builder#294]
The Konvoy 2.1.1 docs currently state to use the latest version of KIB: https://docs.d2iq.com/dkp/konvoy/2.1/image-builder/create-ami/

The latest version fails when using Kommander due to APIs being removed: https://kubernetes.io/blog/2021/08/04/kubernetes-1-22-release-announcement/#removal-of-several-deprecated-beta-apis

Docs should be updated accordingly to make note of incompatibilities, and if 1.9.0+ is intended to be used with Konvoy 2.1.1 there should be details telling you to use `--kubernetes-version=1.22.8` as a parameter with the dkp cli.

**Comment by cmastr** [comment]
We need to version KIB with specific versions of Konvoy and then document properly those version compatibilities. This is on our backlog.

**Comment by faiq** [comment]
Our new docs have mapped versions of dkp to kib https://docs.d2iq.com/dkp/2.4/konvoy-image-builder#id-(2.4)KonvoyImageBuilder-compatible-versionsCompatibleVersions

which match the kubernetes versions, kib versions, and dkp versions accordingly
