### ISSUE TITLE
Support USGovernmentCloud in Azure image builds

### ISSUE THREAD

**Issue by ericgoode** [mesosphere/konvoy-image-builder#444]
As a developer, I need to do Azure image builds against USGovernmentCloud. 

Currently, there is no way to set the Azure cloud environment. We were able to set the Packer overrides for this in the Kubernetes Image Builder, but found no way to pass the correct values to the Azure Go SDK that is used.

**Comment by faiq** [comment]
Resolved and released in version 1.20.0
