### ISSUE TITLE
mesosphere/konvoy is missing an official docker image for Linux/ARM64

### ISSUE THREAD

**Issue by odidev** [mesosphere/konvoy-image-builder#60]
Hi Team,

I worked on building Linux/ARM64 Docker image for mesosphere/konvoy. 

I have explored the Dockerfiles present in the github repository, but it seems that the content does not match with the content of Konvoy Docker image present at Docker hub.

 Please have a look here: 

<https://hub.docker.com/layers/mesosphere/konvoy/v1.8.2_ubi8/images/sha256-589aa972b7abc6aa3edf2a7865eb94915ff056c161487e917952d8fc9ffaef08?context=explore>.

It would be really helpful, if konvoy docker image is available for Linux/ARM64. 

Could you please point me to the Docker file for mesosphere/konvoy?

**Comment by jkoelker** [comment]
`konvoy-image-builder` is a tool to create AMI images for Cluster API managed kubernetes clusters. The docker hub link is from `konvoy` which is a older tool to create a cluster without using Cluster API. Unfortunately `konvoy` is not opensource.
